"""rename department

Revision ID: e98b9963be16
Revises: ba18ccbffd87
Create Date: 2024-04-02 15:02:00.700887

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e98b9963be16'
down_revision = 'ba18ccbffd87'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("departments","address" ,new_column_name = "location")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("departments","location", new_column_name = "address")
    # ### end Alembic commands ###
